// Item icon pixel art (16x16). Tools/armor use templates with per-material palettes; many
// materials share generic shapes (lump, ingot, gem, dust, ball, rod, egg) with distinct colors.
(function () {
  var ICONS = {};
  function cv() { var c = document.createElement('canvas'); c.width = 16; c.height = 16; return c; }
  function hex(h) { return '#' + ('000000' + h.toString(16)).slice(-6); }
  function shade(h, k) { var r = (h >> 16) & 255, g = (h >> 8) & 255, b = h & 255; return ((Math.min(255, r * k) & 255) << 16) | ((Math.min(255, g * k) & 255) << 8) | (Math.min(255, b * k) & 255); }
  function art(ctx, rows, pal, ox, oy) {
    ox = ox || 0; oy = oy || 0;
    for (var y = 0; y < rows.length; y++) for (var x = 0; x < rows[y].length; x++) {
      var ch = rows[y][x]; if (ch === '.' || ch === ' ') continue; var c = pal[ch]; if (c === undefined) continue;
      ctx.fillStyle = typeof c === 'number' ? hex(c) : c; ctx.fillRect(x + ox, y + oy, 1, 1);
    }
  }
  function icon(name, rows, pal, ox, oy) { var c = cv(); art(c.getContext('2d'), rows, pal, ox, oy); ICONS[name] = c; return c; }
  // material palette: P main, p highlight, s shade, d outline
  function mat(main) { return { P: main, p: shade(main, 1.3), s: shade(main, 0.72), d: shade(main, 0.35) }; }
  var HANDLE = { H: 0x9c7a46, h: 0x6e522c, d: 0x2a1d10, g: 0x5e4630 };
  var TOOL_MATS = { wooden: 0x8a6535, stone: 0x8a8a8a, iron: 0xd8d8d8, golden: 0xf5d341, diamond: 0x4fe0d8, netherite: 0x4d4448 };
  var ARMOR_MATS = { leather: 0xa0693b, chainmail: 0x9a9a9a, iron: 0xd8d8d8, golden: 0xf5d341, diamond: 0x4fe0d8, netherite: 0x4d4448 };

  var SWORD = ['.............ddd', '............dpPd', '...........dpPsd', '..........dpPsd.', '.........dpPsd..', '........dpPsd...', '.......dpPsd....', '...dd.dpPsd.....', '..dggdpPsd......', '...dggPsd.......', '....dggd........', '...ddgdgd.......', '..dhhd.dgd......', '.dhhd...dd......', 'dhhd............', 'ddd.............'];
  var PICKAXE = ['.......ddddd....', '.....ddPpPPPdd..', '....dPPpPpPPPPd.', '...dPPsddhddsPPd', '..dPPd..dHd.dsPd', '..dPd..dHhd..dsd', '.dPd..dHhd....dd', '.dd..dHhd.......', '.d..dHhd........', '...dHhd.........', '..dHhd..........', '.dHhd...........', 'dHhd............', 'dhd.............', 'dd..............', '................'];
  var AXE = ['.........dddd...', '........dPpPPd..', '.......dPpPPPsd.', '......dPPPddPPsd', '.....dPPPdHhdPsd', '....dPPsdHhd.dsd', '....dPPdHhd...dd', '.....ddHhd......', '.....dHhd.......', '....dHhd........', '...dHhd.........', '..dHhd..........', '.dHhd...........', 'dHhd............', 'dhd.............', 'dd..............'];
  var SHOVEL = ['...........ddd..', '..........dPpPd.', '.........dPpPPPd', '.........dPPPsPd', '.........dPPssd.', '........dHhdsd..', '.......dHhd.d...', '......dHhd......', '.....dHhd.......', '....dHhd........', '...dHhd.........', '..dHhd..........', '.dHhd...........', 'dHhd............', 'dhd.............', 'dd..............'];
  var HOE = ['................', '................', '.........ddddd..', '........dPpPPPd.', '.......dPpPddsd.', '......dHhddd.dd.', '.....dHhd.......', '....dHhd........', '...dHhd.........', '..dHhd..........', '.dHhd...........', 'dHhd............', 'dhd.............', 'dd..............', '................', '................'];
  var HELMET = ['................', '................', '................', '....dddddddd....', '...dPPPPPPPPd...', '..dPpPPPPPPPsd..', '..dPPPPPPPPPsd..', '..dPPPPPPPPPsd..', '..dPPPPPPPPPsd..', '..dPPPddddPPsd..', '..dPPd....dPsd..', '..dPsd....dssd..', '..dddd....dddd..', '................', '................', '................'];
  var CHEST = ['................', '.ddddd....ddddd.', '.dPPPPd..dPPPPd.', '.dPpPPddddPPPPd.', '.dPPPPPPPPPPPPd.', '.dPdPPPPPPPPdsd.', '.ddddPPPPPPdddd.', '....dPPPPPPd....', '....dPPPPPPd....', '....dPPPPPPd....', '....dPPPPPPd....', '....dPPPPPsd....', '....dPPPPssd....', '....dddddddd....', '................', '................'];
  var LEGS = ['................', '..dddddddddddd..', '..dPPPPPPPPPPd..', '..dPpPPPPPPPsd..', '..dPPPPddPPPsd..', '..dPPPd..dPPsd..', '..dPPPd..dPPsd..', '..dPPPd..dPPsd..', '..dPPPd..dPPsd..', '..dPPPd..dPPsd..', '..dPPPd..dPPsd..', '..dPPsd..dPssd..', '..ddddd..ddddd..', '................', '................', '................'];
  var BOOTS = ['................', '................', '................', '..dddd....dddd..', '..dPPd....dPPd..', '..dpPd....dpPd..', '..dPPd....dPPd..', '..dPPd....dPPd..', '..dPPd....dPPd..', '.ddPPd....dPPdd.', 'dPPPPd....dPPPPd', 'dPPPsd....dPPPsd', 'dddddd....dddddd', '................', '................', '................'];
  var LUMP = ['................', '................', '................', '.....dddd.......', '....dPpPPd......', '...dPpPPPPd.....', '..dPPPPPPPPd....', '..dPPPPPPPsd....', '..dPPPPPPssd....', '...dPPPsssd.....', '....dsssd.......', '.....dddd.......', '................', '................', '................', '................'];
  var INGOT = ['................', '................', '................', '................', '................', '......ddddddd...', '.....dPppppPPd..', '....dPPPPPPPPsd.', '...dPPPPPPPPssd.', '..dssPPPPPssssd.', '..dsssssssssdd..', '...ddddddddd....', '................', '................', '................', '................'];
  var GEM = ['................', '................', '................', '.....dddddd.....', '....dpPPPPsd....', '...dpPPPPPPsd...', '..dpPPPPPPPPsd..', '..dPPPPPPPPssd..', '...dPPPPPPssd...', '....dPPPPssd....', '.....dPPssd.....', '......dssd......', '.......dd.......', '................', '................', '................'];
  var DUST = ['................', '................', '................', '................', '................', '................', '................', '......dd........', '....ddPPd.......', '...dPpPPPd.dd...', '..dPPPPPPddPPd..', '.dPPpPPPPPPPPsd.', 'dPPPPPPPPsPPssd.', 'dsPPPPPsssssssd.', '.ddddddddddddd..', '................'];
  var BALL = ['................', '................', '................', '.....dddddd.....', '...ddPppPPPdd...', '..dPpPPPPPPPsd..', '.dPpPPPPPPPPssd.', '.dPPPPPPPPPPssd.', '.dPPPPPPPPPsssd.', '.dPPPPPPPPssssd.', '..dPPPPPPssssd..', '...ddsssssssdd..', '.....dddddd.....', '................', '................', '................'];
  var EGG = ['................', '................', '......dddd......', '.....dPppPd.....', '....dPpPPPPd....', '...dPpPPPPPPd...', '...dPPPPPPPsd...', '..dPPPPPPPPssd..', '..dPPPPPPPPssd..', '..dPPPPPPPsssd..', '..dPPPPPPsssd...', '...dPPPPssssd...', '....dPPssssd....', '.....ddsssd.....', '.......ddd......', '................'];
  var ROD = ['................', '.............dd.', '............dPd.', '...........dPPd.', '..........dPPd..', '.........dPPd...', '........dPPd....', '.......dPPd.....', '......dPPd......', '.....dPPd.......', '....dPPd........', '...dPPd.........', '..dPPd..........', '.dPPd...........', '.dPd............', '.dd.............'];
  var BOTTLE = ['................', '......dddd......', '......dwwd......', '......dwwd......', '.....ddwwdd.....', '....dwwPPwwd....', '...dwPPPPPPwd...', '...dPPPPPPPPd...', '...dPPPPPPPPd...', '...dPPPPPPPPd...', '...dPPPPPPPPd...', '...dPPPPPPPPd...', '...dsPPPPPPsd...', '....dsPPPPsd....', '.....dddddd.....', '................'];
  var DISC = ['................', '................', '.....dddddd.....', '...ddkkkkkkdd...', '..dkkPPkkkkkkd..', '.dkkPkkkkkkkkkd.', '.dkPkkkkkkkkkkd.', 'dkkkkkkddkkkkkkd', 'dkkkkkkddkkkkkkd', '.dkkkkkkkkkkkkd.', '.dkkkkkkkkkkPkd.', '..dkkkkkkkkPkd..', '...ddkkkkkkdd...', '.....dddddd.....', '................', '................'];
  var MEAT = ['................', '................', '................', '.....ddd........', '....dwwwdd......', '...dwPPPPwd.....', '..dwPPPPPPPd....', '..dPPPPPPPPd....', '..dPPPPPPPPsd...', '..dPPPPPPPssd...', '...dPPPPPsssd...', '....dPPPsssd....', '.....dsssdd.....', '......ddd.......', '................', '................'];
  var FISH = ['................', '................', '................', '................', '..d..........d..', '..dd.....ddddd..', '..dPd..ddPPPPd..', '..dPPddPPPPPPd..', '..dPPPPPPPPPePd.', '..dPPPPPPPPPPPd.', '..dPPddPPPPPPd..', '..dPd..ddPPPPd..', '..dd.....ddddd..', '..d..........d..', '................', '................'];

  function tool(kind, rows) {
    Object.keys(TOOL_MATS).forEach(function (m) {
      var pal = Object.assign({}, HANDLE, mat(TOOL_MATS[m])); pal.d = m === 'wooden' ? 0x2a1d10 : shade(TOOL_MATS[m], 0.3); if (m === 'wooden') { pal.P = 0x8a6535; pal.p = 0xa88048; pal.s = 0x6a4a25; }
      icon(m + '_' + kind, rows, pal);
    });
  }
  function armor(kind, rows) { Object.keys(ARMOR_MATS).forEach(function (m) { var pal = mat(ARMOR_MATS[m]); pal.d = shade(ARMOR_MATS[m], 0.3); icon(m + '_' + kind, rows, pal); if (m === 'chainmail') { var ctx = ICONS[m + '_' + kind].getContext('2d'); ctx.fillStyle = hex(0x6a6a6a); for (var y = 2; y < 14; y++) for (var x = 2; x < 14; x++) if ((x + y) % 2 === 0 && rows[y] && rows[y][x] === 'P') ctx.fillRect(x, y, 1, 1); } }); }
  function generic(name, rows, main, extra) { var pal = mat(main); pal.d = shade(main, 0.3); if (extra) Object.assign(pal, extra); return icon(name, rows, pal); }

  function build() {
    if (ICONS.stick) return;
    tool('sword', SWORD); tool('pickaxe', PICKAXE); tool('axe', AXE); tool('shovel', SHOVEL); tool('hoe', HOE);
    armor('helmet', HELMET); armor('chestplate', CHEST); armor('leggings', LEGS); armor('boots', BOOTS);

    generic('stick', ROD, 0x8f6a3a);
    generic('blaze_rod', ROD, 0xf6a11a, { p: 0xffe07a });
    generic('bone', ROD, 0xe8e8e0, { p: 0xffffff });
    generic('coal', LUMP, 0x2b2b2b, { p: 0x4a4a4a, d: 0x0a0a0a });
    generic('charcoal', LUMP, 0x3a3230, { p: 0x5a504c, d: 0x140f0d });
    generic('raw_iron', LUMP, 0xd6b29a); generic('raw_gold', LUMP, 0xf2d05a); generic('raw_copper', LUMP, 0xd0805a);
    generic('clay_ball', BALL, 0xa4acbd); generic('snowball', BALL, 0xf2f6ff, { p: 0xffffff }); generic('slime_ball', BALL, 0x78c85a, { p: 0xa8e888 });
    generic('ender_pearl', BALL, 0x0f5f5f, { p: 0x2fa89a, s: 0x083838 }); generic('magma_cream', BALL, 0xd88a2a, { p: 0xffd060 }); generic('ghast_tear', GEM, 0xd8f2f0, { p: 0xffffff });
    generic('iron_ingot', INGOT, 0xd8d8d8); generic('gold_ingot', INGOT, 0xf5d341); generic('copper_ingot', INGOT, 0xd0805a); generic('netherite_ingot', INGOT, 0x4d4448, { p: 0x6a6068 }); generic('brick', INGOT, 0xb5604a); generic('nether_brick', INGOT, 0x3e1f24, { p: 0x5a3038 }); generic('netherite_scrap', LUMP, 0x6e5a55);
    generic('iron_nugget', LUMP, 0xd8d8d8); generic('gold_nugget', LUMP, 0xf5d341);
    generic('diamond', GEM, 0x4fe0d8, { p: 0xc2fffb }); generic('emerald', GEM, 0x2fc76a, { p: 0x9df7bd }); generic('quartz', GEM, 0xe8e2dc, { p: 0xffffff }); generic('amethyst_shard', GEM, 0x9a6fd6, { p: 0xd0b8ff }); generic('prismarine_shard', GEM, 0x7fbfb2, { p: 0xc4f0e8 }); generic('prismarine_crystals', GEM, 0xbfe8dc, { p: 0xffffff }); generic('lapis_lazuli', LUMP, 0x2a4fb0, { p: 0x5a80e0 }); generic('flint', LUMP, 0x4a4a4a, { p: 0x6a6a6a, d: 0x1a1a1a }); generic('heart_of_the_sea', BALL, 0x2f7fb8, { p: 0x8ad8ff }); generic('nether_star', GEM, 0xfff6c8, { p: 0xffffff });
    generic('redstone', DUST, 0xd41e1e, { p: 0xff5a5a }); generic('glowstone_dust', DUST, 0xf2d23a, { p: 0xfff08a }); generic('gunpowder', DUST, 0x6a6a6a, { p: 0x8f8f8f }); generic('sugar', DUST, 0xf2f2f2, { p: 0xffffff }); generic('bone_meal', DUST, 0xe8e8e0, { p: 0xffffff }); generic('blaze_powder', DUST, 0xf6a11a, { p: 0xffe07a });
    generic('egg', EGG, 0xe8dcc8, { p: 0xfff8ea }); generic('experience_bottle', BOTTLE, 0xd4e83a, { w: 0xc8e8ff, p: 0xf0ff80 }); generic('glass_bottle', BOTTLE, 0xd0e8ff, { w: 0xc8e8ff, p: 0xffffff }); generic('dragon_breath', BOTTLE, 0xd85ad8, { w: 0xc8e8ff, p: 0xff9aff }); generic('honey_bottle', BOTTLE, 0xf0a832, { w: 0xc8e8ff });
    generic('music_disc_13', DISC, 0x2a2a2a, { k: 0x1a1a1a, p: 0x777777 }); generic('music_disc_cat', DISC, 0x2a2a2a, { k: 0x1a1a1a, p: 0x8ac83a });
    generic('porkchop', MEAT, 0xf09a9a, { w: 0xffffff, p: 0xffc8c8 }); generic('cooked_porkchop', MEAT, 0xb27045, { w: 0xe8d8b8 }); generic('beef', MEAT, 0xc23a3a, { w: 0xffffff }); generic('cooked_beef', MEAT, 0x7a4a2a, { w: 0xd8c8a8 }); generic('chicken', MEAT, 0xf0c0a0, { w: 0xffffff }); generic('cooked_chicken', MEAT, 0xc08048, { w: 0xffffff }); generic('mutton', MEAT, 0xd04848, { w: 0xffffff }); generic('cooked_mutton', MEAT, 0x8a4a2a, { w: 0xd8c8a8 }); generic('rotten_flesh', MEAT, 0x8a5a3a, { w: 0x6a8a3a, p: 0xa07050 }); generic('rabbit_hide', MEAT, 0xa07a5a, { w: 0xd0b090 });
    generic('cod', FISH, 0xb8a888, { e: 0x000000 }); generic('cooked_cod', FISH, 0xd8b888, { e: 0x000000 }); generic('salmon', FISH, 0xb84a3a, { e: 0x000000 }); generic('cooked_salmon', FISH, 0xc86a4a, { e: 0x000000 });
    icon('apple', ['................', '.......dd.......', '......dgd.......', '......dd........', '...ddddddd......', '..dRRrrdrrRd....', '.dRRRrrrrrrRd...', '.dRRRRrrrrrrd...', '.dRRRRRrrrrrd...', '.dRRRRRrrrrrd...', '.dRRRRRRrrrrd...', '..dRRRRRrrrd....', '...ddRRRrdd.....', '.....ddddd......', '................', '................'], { d: 0x3a0a0a, g: 0x4a9a2a, R: 0xff2a2a, r: 0xd41e1e });
    icon('golden_apple', ['................', '.......dd.......', '......dgd.......', '......dd........', '...ddddddd......', '..dYYyydyyYd....', '.dYYYyyyyyyYd...', '.dYYYYyyyyyyd...', '.dYYYYYyyyyyd...', '.dYYYYYyyyyyd...', '.dYYYYYYyyyyd...', '..dYYYYYyyyd....', '...ddYYYydd.....', '.....ddddd......', '................', '................'], { d: 0x6a4a00, g: 0x4a9a2a, Y: 0xfff08a, y: 0xf5d341 });
    icon('carrot', ['................', '.............gg.', '...........gggg.', '..........ggg...', '.........dggd...', '........dOod....', '.......dOOod....', '......dOOod.....', '.....dOOod......', '....dOOod.......', '...dOOod........', '..dOOod.........', '.dOod...........', '.dod............', '.dd.............', '................'], { d: 0x7a3a10, g: 0x3f9a2a, O: 0xf58a2a, o: 0xd06a1a });
    icon('golden_carrot', ['................', '.............gg.', '...........gggg.', '..........ggg...', '.........dggd...', '........dYyd....', '.......dYYyd....', '......dYYyd.....', '.....dYYyd......', '....dYYyd.......', '...dYYyd........', '..dYYyd.........', '.dYyd...........', '.dyd............', '.dd.............', '................'], { d: 0x8a6a10, g: 0x3f9a2a, Y: 0xfff08a, y: 0xf5d341 });
    icon('potato', ['................', '................', '................', '................', '.....dddddd.....', '....dPppPPPd....', '...dPpPPPPPPd...', '..dPPPPPPPPPsd..', '..dPPPPPPPPPsd..', '..dPPPPPPPPssd..', '...dPPPPPPssd...', '....dPPPsssd....', '.....dddddd.....', '................', '................', '................'], { d: 0x6a4a20, P: 0xd8b060, p: 0xf0d090, s: 0xb08840 });
    icon('baked_potato', ['................', '................', '................', '................', '.....dddddd.....', '....dPppPPPd....', '...dPpPPPPPPd...', '..dPPPPPPPPPsd..', '..dPPPkPPPPPsd..', '..dPPPPPPkPssd..', '...dPPPPPPssd...', '....dPPPsssd....', '.....dddddd.....', '................', '................', '................'], { d: 0x5a3a10, P: 0xc09040, p: 0xe0b060, s: 0x906820, k: 0x6a4010 });
    icon('poisonous_potato', LUMP, { d: 0x4a5a20, P: 0xa8b860, p: 0xd0d890, s: 0x788838 });
    icon('beetroot', ['................', '................', '.......gg.......', '......gggg......', '.......gg.......', '.....dddddd.....', '....dRrrRRRd....', '...dRrrRRRRRd...', '...dRRRRRRRRd...', '...dRRRRRRRsd...', '....dRRRRRssd...', '.....dRRRssd....', '......dRssd.....', '.......dsd......', '........d.......', '................'], { d: 0x3a0a1a, g: 0x3f9a2a, R: 0xa8203a, r: 0xd0405a, s: 0x7a1428 });
    icon('melon_slice', ['................', '..............d.', '.............dGd', '............dGgd', '...........dGrgd', '..........dGrrgd', '.........dGrrrgd', '........dGrrkrgd', '.......dGrrrrrgd', '......dGrrkrrrgd', '.....dGrrrrrkrgd', '....dGrrrrrrrrgd', '...dGgggggggggd.', '..ddddddddddddd.', '................', '................'], { d: 0x1a3a0a, G: 0x9fbf2a, g: 0x6f9a1f, r: 0xe83a3a, k: 0x1a1a1a });
    icon('sweet_berries', ['................', '................', '.....gg.........', '....gggg..gg....', '...dd.gg.gggg...', '..dRRd.dd.gg....', '..dRrd.dRRd.....', '...dd.dRRrd.....', '.....ddRRd.dd...', '....dRRddd.dRRd.', '....dRrd..dRRrd.', '.....dd....ddd..', '................', '................', '................', '................'], { d: 0x3a0a10, g: 0x3f9a2a, R: 0xd02a3a, r: 0xff6a7a });
    icon('glow_berries', ['................', '................', '.....gg.........', '....gggg..gg....', '...dd.gg.gggg...', '..dYYd.dd.gg....', '..dYyd.dYYd.....', '...dd.dYYyd.....', '.....ddYYd.dd...', '....dYYddd.dYYd.', '....dYyd..dYYyd.', '.....dd....ddd..', '................', '................', '................', '................'], { d: 0x6a5a10, g: 0x3f9a2a, Y: 0xffd23f, y: 0xfff0a0 });
    icon('bread', ['................', '................', '................', '................', '..........ddd...', '........ddPPPd..', '......ddPpPPPPd.', '....ddPpPPPPPPd.', '..ddPpPPPPPPPsd.', '.dPpPPPPPPPPssd.', '.dPPPPPPPPPsssd.', '.dsPPPPPPPsssd..', '..ddssssssddd...', '....dddddd......', '................', '................'], { d: 0x5a3a10, P: 0xc08a3a, p: 0xe0b060, s: 0x9a6a25 });
    icon('cookie', ['................', '................', '................', '................', '.....dddddd.....', '...ddPPkPPPdd...', '..dPPPPPPPkPPd..', '..dPkPPPPPPPPd..', '.dPPPPPkPPPPPPd.', '.dPPPPPPPPPkPPd.', '.dPkPPPPPPPPPPd.', '..dPPPPkPPPPsd..', '..dPPPPPPPkPsd..', '...ddPPPPPPdd...', '.....dddddd.....', '................'], { d: 0x5a3a10, P: 0xc08a3a, k: 0x4a2a10 });
    icon('pumpkin_pie', ['................', '................', '................', '................', '.....dddddd.....', '...ddwwwwwwdd...', '..dwwwwwwwwwwd..', '.dwwOOOOOOOOwwd.', '.dOOOOOOoOOOOOd.', '.dOOOoOOOOOOOOd.', '.dsOOOOOOOoOOsd.', '..dssOOOOOOssd..', '...ddsssssddd...', '.....dddddd.....', '................', '................'], { d: 0x5a3a10, w: 0xe8d8b8, O: 0xd88a3a, o: 0xf0a850, s: 0xb06a25 });
    icon('mushroom_stew', ['................', '................', '................', '................', '....dddddddd....', '..ddPPPPPPPPdd..', '.dPPmmPPPPmmPPd.', '.dPPPPPPPPPPPPd.', '..dwwwwwwwwwwd..', '..dwwwwwwwwwwd..', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '....dwwwwwwd....', '.....dddddd.....', '................', '................'], { d: 0x3a2a10, P: 0xb87a3a, m: 0xd8d8c0, w: 0x8a5a2a });
    icon('spider_eye', ['................', '................', '................', '................', '.....dddddd.....', '....dRRRRRRd....', '...dRRRRRRRRd...', '..dRRRkkkkRRRd..', '..dRRkkwkkkRRd..', '..dRRkkkkkkRRd..', '..dRRRkkkkRRRd..', '...dRRRRRRRRd...', '....dRRRRRRd....', '.....dddddd.....', '................', '................'], { d: 0x3a0a0a, R: 0x9a1a2a, k: 0x1a0a0a, w: 0xffffff });
    icon('ender_eye', ['................', '................', '................', '................', '.....dddddd.....', '....dGGGGGGd....', '...dGGGGGGGGd...', '..dGGGkkkkGGGd..', '..dGGkkwkkkGGd..', '..dGGkkkkkkGGd..', '..dGGGkkkkGGGd..', '...dGGGGGGGGd...', '....dGGGGGGd....', '.....dddddd.....', '................', '................'], { d: 0x0a3a2a, G: 0x8ad8a0, k: 0x104a3a, w: 0xffffff });
    icon('wheat', ['................', '......y.y.......', '.....yyyy.y.....', '.....yyyyyy.....', '....yyyyyyy.....', '.....yyyyyy.....', '....yyyyyyyy....', '.....yyyyyy.....', '......gyyg......', '......g..g......', '......g..g......', '.....g..g.......', '.....g..g.......', '.....g..g.......', '....g..g........', '................'], { y: 0xd6b84a, g: 0x8a9a3a });
    icon('wheat_seeds', ['................', '................', '................', '................', '.....g..........', '....ggg.....g...', '.....g.....ggg..', '........g...g...', '..g....ggg......', '.ggg....g...g...', '..g........ggg..', '......g.....g...', '.....ggg........', '......g.........', '................', '................'], { g: 0x3f9a2a });
    icon('beetroot_seeds', ['................', '................', '................', '................', '.....g..........', '....ggg.....g...', '.....g.....ggg..', '........g...g...', '..g....ggg......', '.ggg....g...g...', '..g........ggg..', '......g.....g...', '.....ggg........', '......g.........', '................', '................'], { g: 0xa8303a });
    icon('melon_seeds', ['................', '................', '................', '................', '.....g..........', '....ggg.....g...', '.....g.....ggg..', '........g...g...', '..g....ggg......', '.ggg....g...g...', '..g........ggg..', '......g.....g...', '.....ggg........', '......g.........', '................', '................'], { g: 0x2a2a2a });
    icon('pumpkin_seeds', ['................', '................', '................', '................', '.....g..........', '....ggg.....g...', '.....g.....ggg..', '........g...g...', '..g....ggg......', '.ggg....g...g...', '..g........ggg..', '......g.....g...', '.....ggg........', '......g.........', '................', '................'], { g: 0xe8e0a8 });
    icon('feather', ['................', '..............d.', '.............dwd', '............dwwd', '...........dwwwd', '..........dwWwd.', '.........dwWwwd.', '........dwWwwd..', '.......dwWwwd...', '......dwWwwd....', '.....dwWwd......', '....dwWwd.......', '...dwwd.........', '..dhd...........', '.dhd............', '.d..............'], { d: 0x3a3a3a, w: 0xe8e8e8, W: 0xffffff, h: 0x9a9a9a });
    icon('leather', ['................', '................', '................', '...dddd..ddd....', '..dPPPPddPPPd...', '.dPpPPPPPPPPPd..', '.dPPPPPPPPPPPd..', '.dPPPPPPPPPPsd..', '..dPPPPPPPPPsd..', '..dPPPPPPPPssd..', '...dPPPPPPssd...', '...dPPPPPsssd...', '....dPPddssd....', '.....dd..dd.....', '................', '................'], { d: 0x4a2a10, P: 0xa0693b, p: 0xc08a55, s: 0x7a4a25 });
    icon('string', ['................', '.....dd.........', '....dwwd........', '...dw..wd.......', '...dw..wd.......', '....dwwd........', '.....dwd........', '.....dwd........', '.....dwwd.......', '......dwwd......', '.......dwwd.....', '........dwwd....', '.........dwwd...', '..........dwd...', '...........d....', '................'], { d: 0x9a9a9a, w: 0xf0f0f0 });
    icon('paper', ['................', '................', '....dddddddd....', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '...dwwwwwwwwd...', '....dddddddd....', '................', '................'], { d: 0x9a9a9a, w: 0xf4f4f4 });
    icon('book', ['................', '................', '..dddddddddd....', '.dRRRRRRRRRRdd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRrrRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRdd..', '..dddddddddd....', '................', '................'], { d: 0x3a2a14, R: 0xa0693b, r: 0xc08a55, w: 0xf0e8d8 });
    icon('enchanted_book', ['................', '................', '..dddddddddd....', '.dRRRRRRRRRRdd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRyRRRRRwd..', '.dRrrRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRyRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRdd..', '..dddddddddd....', '................', '................'], { d: 0x3a2a14, R: 0x8a4a4a, r: 0xa06060, w: 0xf0e8d8, y: 0xffe080 });
    icon('writable_book', ['................', '................', '..dddddddddd....', '.dRRRRRRRRRRdd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRrrRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRwd..', '.dRRRRRRRRRRdd..', '..dddddddddd....', '......ff........', '................'], { d: 0x3a2a14, R: 0x6a5a4a, r: 0x8a7a6a, w: 0xf0e8d8, f: 0xf0f0f0 });
    icon('bucket', ['................', '................', '.....dddddd.....', '....dwwwwwwd....', '...dw......wd...', '...dPPPPPPPPd...', '...dpPPPPPPsd...', '....dPPPPPsd....', '....dPPPPPsd....', '....dPPPPPsd....', '....dPPPPPsd....', '.....dPPPsd.....', '.....dPPPsd.....', '.....dPPPsd.....', '......dddd......', '................'], { d: 0x3a3a3a, w: 0xa0a0a0, P: 0xa8a8a8, p: 0xd0d0d0, s: 0x7a7a7a });
    function bucketOf(name, fill) { icon(name, ['................', '................', '.....dddddd.....', '....dwwwwwwd....', '...dw......wd...', '...dPPPPPPPPd...', '...dFFFFFFFFd...', '....dFFFFFFd....', '....dPPPPPsd....', '....dPPPPPsd....', '....dPPPPPsd....', '.....dPPPsd.....', '.....dPPPsd.....', '.....dPPPsd.....', '......dddd......', '................'], { d: 0x3a3a3a, w: 0xa0a0a0, P: 0xa8a8a8, s: 0x7a7a7a, F: fill }); }
    bucketOf('water_bucket', 0x3f76e4); bucketOf('lava_bucket', 0xf07a1a); bucketOf('milk_bucket', 0xffffff);
    icon('flint_and_steel', ['................', '........dd......', '.......dPPd.....', '......dPppPd....', '.....dPPPPPPd...', '....dPPPPPPPd...', '...dPPPPPPPd....', '..dPPPPPPPd.....', '..dPPPPPPd......', '.ddPPPPPd.......', 'dkkdPPPd........', 'dkkkdPd.........', 'dkkkkd..........', '.dkkkd..........', '..ddd...........', '................'], { d: 0x2a2a2a, P: 0xa8a8a8, p: 0xd8d8d8, k: 0x5a5a5a });
    icon('shears', ['................', '..............d.', '.............dPd', '............dPPd', '...........dPPd.', '..........dPPd..', '...d.....dPPd...', '..dPd...dPPd....', '...dPd.dPPd.....', '....dPdPPd......', '.....dPPd.......', '....ddddd.......', '...dRRdRRd......', '..dRRRdRRRd.....', '...dRRdRRd......', '....dd.dd.......'], { d: 0x2a2a2a, P: 0xc8c8c8, R: 0x8a3a3a });
    icon('bow', ['................', '.......dd.......', '......dPPd......', '.....dPd.dd.....', '....dPd...w.....', '...dPd....w.....', '...dPd....w.....', '..dPd.....w.....', '..dPd.....w.....', '..dPd.....w.....', '...dPd....w.....', '...dPd....w.....', '....dPd...w.....', '.....dPd.dd.....', '......dPPd......', '.......dd.......'], { d: 0x3a2a14, P: 0xa0693b, w: 0xe8e8e8 });
    icon('arrow', ['................', '.............dd.', '............dwwd', '...........dwwwd', '..........dhdwwd', '.........dhd.dd.', '........dhd.....', '.......dhd......', '......dhd.......', '.....dhd........', '....dhd.........', '..fdhd..........', '.fffd...........', 'fffff...........', '.fff............', '..f.............'], { d: 0x3a3a3a, w: 0xd8d8d8, h: 0x9c7a46, f: 0xf0f0f0 });
    icon('compass', ['................', '................', '.....dddddd.....', '...ddPPPPPPdd...', '..dPPPPkkPPPPd..', '.dPPPPkkkkPPPPd.', '.dPPPkkRRkkPPPd.', 'dPPPPkkRRkkPPPPd', 'dPPPPkkwwkkPPPPd', '.dPPPkkwwkkPPPd.', '.dPPPPkkkkPPPPd.', '..dPPPPkkPPPPd..', '...ddPPPPPPdd...', '.....dddddd.....', '................', '................'], { d: 0x3a3a3a, P: 0x9a9a9a, k: 0x2a2a3a, R: 0xff2020, w: 0xf0f0f0 });
    icon('clock', ['................', '................', '.....dddddd.....', '...ddPPPPPPdd...', '..dPPPPbbPPPPd..', '.dPPPPbbbbPPPPd.', '.dPPPbbyybbPPPd.', 'dPPPPbbyybbPPPPd', 'dPPPPbbbbbbPPPPd', '.dPPPbbbbbbPPPd.', '.dPPPPbbbbPPPPd.', '..dPPPPbbPPPPd..', '...ddPPPPPPdd...', '.....dddddd.....', '................', '................'], { d: 0x6a4a10, P: 0xf5d341, b: 0x3a5a9a, y: 0xffe080 });
    icon('spyglass', ['................', '.............dd.', '............dPPd', '...........dPPd.', '..........dPPd..', '.........dCCd...', '........dCCd....', '.......dCCd.....', '......dCCd......', '.....dCCd.......', '....dCCd........', '...dCCd.........', '..dCCd..........', '.dPPd...........', '.dPd............', '.dd.............'], { d: 0x3a2a14, P: 0xd0805a, C: 0xb06a48 });
    icon('fishing_rod', ['................', '.............dd.', '............dwd.', '...........dPdw.', '..........dPd.w.', '.........dPd..w.', '........dPd...w.', '.......dPd....w.', '......dPd.....w.', '.....dPd......w.', '....dPd.....dww.', '...dPd.....dkkd.', '..dPd......dkkd.', '.dPd........dd..', '.dd.............', '................'], { d: 0x3a2a14, P: 0xa0693b, w: 0xe0e0e0, k: 0x9a9a9a });
    icon('shield', ['................', '..dddddddddddd..', '.dPPPPPPwwPPPPd.', '.dPPPPPPwwPPPPd.', '.dPPPPPPwwPPPPd.', '.dwwwwwwwwwwwwd.', '.dwwwwwwwwwwwwd.', '.dPPPPPPwwPPPPd.', '.dPPPPPPwwPPPPd.', '..dPPPPPwwPPPd..', '..dPPPPPwwPPPd..', '...dPPPPwwPPd...', '....dPPPwwPd....', '.....dPPwPd.....', '......dddd......', '................'], { d: 0x3a2a14, P: 0x8a5a2a, w: 0xd8d8d8 });
    icon('elytra', ['................', '.......dd.......', '......dPPd......', '.....dPPPPd.....', '....dPPddPPd....', '...dPPd..dPPd...', '..dPPd....dPPd..', '..dPPd....dPPd..', '.dPPd......dPPd.', '.dPPd......dPPd.', '.dPd........dPd.', '.dPd........dPd.', '.dd..........dd.', '................', '................', '................'], { d: 0x3a3a4a, P: 0x8a8a9a });
    icon('trident', ['................', '.............dd.', '............dPd.', '..........ddPPd.', '.........dPPPd..', '..........dPd...', '.........dPd....', '........dPd.....', '.......dPd......', '......dPd.......', '.....dPd........', '....dPd.........', '...dPd..........', '..dPd...........', '.dPd............', '.dd.............'], { d: 0x1a4a4a, P: 0x4aa8a0 });
    icon('name_tag', ['................', '................', '................', '.....ddddddddd..', '....dwwwwwwwwwd.', '...dwkwwwwwwwwd.', '..dwwwwwwwwwwwd.', '.dwwwwwwwwwwwwd.', '..dwwwwwwwwwwwd.', '...dwwwwwwwwwwd.', '....dwwwwwwwwwd.', '.....ddddddddd..', '................', '................', '................', '................'], { d: 0x3a3a3a, w: 0xe0e0e0, k: 0x3a3a3a });
    icon('saddle', ['................', '................', '................', '................', '....dddd........', '...dPPPPd.......', '..dPPPPPPdddd...', '.dPPPPPPPPPPPd..', '.dPPPPPPPPPPPPd.', '.dPPPPddPPPPPPd.', '..dPPd..dPPPPd..', '..dkd....dkkd...', '..dkd....dkkd...', '...d......dd....', '................', '................'], { d: 0x3a2a14, P: 0x8a5a2a, k: 0x9a9a9a });
    icon('lead', ['................', '.....ddd........', '....dPPPd.......', '...dPd.dPd......', '...dPd.dPd......', '....dPPPd.......', '.....dPd........', '.....dPd........', '......dPd.......', '.......dPd......', '........dPd.....', '.........dPd....', '..........dPd...', '...........dd...', '................', '................'], { d: 0x3a2a14, P: 0xa0693b });
    icon('totem_of_undying', ['................', '.....dddddd.....', '....dGGGGGGd....', '....dGkGGkGd....', '....dGGGGGGd....', '.....dGGGGd.....', 'dddddGGGGGGddddd', 'dYYYYGGGGGGYYYYd', 'ddddddGGGGdddddd', '.....dGGGGd.....', '.....dGGGGd.....', '.....dGGGGd.....', '.....dGGGGd.....', '.....dGGGGd.....', '.....dddddd.....', '................'], { d: 0x4a6a10, G: 0x8ac83a, k: 0x1a1a1a, Y: 0xf5d341 });
    icon('ink_sac', ['................', '................', '................', '.....ddddd......', '....dkkkkkd.....', '...dkkKkkkkd....', '...dkkkkkkkd....', '...dkkkkkkkd....', '....dkkkkkd.....', '.....dkdkd......', '....dkd.dkd.....', '....dkd..dkd....', '.....d....d.....', '................', '................', '................'], { d: 0x0a0a0a, k: 0x1e1e2a, K: 0x3a3a4a });
    icon('glow_ink_sac', ['................', '................', '................', '.....ddddd......', '....dkkkkkd.....', '...dkkKkkkkd....', '...dkkkkkkkd....', '...dkkkkkkkd....', '....dkkkkkd.....', '.....dkdkd......', '....dkd.dkd.....', '....dkd..dkd....', '.....d....d.....', '................', '................', '................'], { d: 0x0a3a3a, k: 0x2aa8a8, K: 0x8af0f0 });
    icon('honeycomb', ['................', '................', '.....dddddd.....', '....dOOoOOOd....', '...dOdOOdOOOd...', '..dOOOdOOdOOOd..', '..dOdOOOOOOdOd..', '..dOOOdOOdOOOd..', '..dOOOOdOOOOOd..', '...dOdOOOOdOd...', '....dOOdOOOd....', '.....dddddd.....', '................', '................', '................', '................'], { d: 0x8a5a10, O: 0xf0a832, o: 0xffd060 });
    icon('nautilus_shell', BALL, { d: 0x5a4a3a, P: 0xd8c8a8, p: 0xf0e8d8, s: 0xa08a6a });
    icon('phantom_membrane', LUMP, { d: 0x3a4a5a, P: 0xa8b8c8, p: 0xd0dce8, s: 0x7a8a9a });
    icon('rabbit_foot', ROD, { d: 0x4a3a2a, P: 0xc8a888, p: 0xe0c8a8, s: 0x9a7a5a });
    icon('turtle_scute', LUMP, { d: 0x2a4a2a, P: 0x4a9a4a, p: 0x7ac87a, s: 0x2a6a2a });
    icon('iron_horse_armor', CHEST, mat(0xd8d8d8)); icon('golden_horse_armor', CHEST, mat(0xf5d341)); icon('diamond_horse_armor', CHEST, mat(0x4fe0d8));
    ['iron_horse_armor', 'golden_horse_armor', 'diamond_horse_armor'].forEach(function (n) { ICONS[n].getContext('2d'); });
    // dyes
    var DYE = { white: 0xf0f0f0, orange: 0xf07613, magenta: 0xbd44b3, light_blue: 0x3aafd9, yellow: 0xf8c627, lime: 0x70b919, pink: 0xed8dac, gray: 0x3e4447, light_gray: 0x8e8e86, cyan: 0x158991, purple: 0x792aac, blue: 0x35399d, brown: 0x724728, green: 0x546d1b, red: 0xa12722, black: 0x1a1a1e };
    Object.keys(DYE).forEach(function (c) { generic(c + '_dye', DUST, DYE[c], { d: shade(DYE[c], 0.4) }); });
    // spawn eggs
    var EGGS = { pig: [0xf0a5a2, 0xdb635f], cow: [0x443626, 0xa1a1a1], sheep: [0xe7e7e7, 0xffb5b5], chicken: [0xa1a1a1, 0xff0000], zombie: [0x00afaf, 0x799c65], creeper: [0x0da70b, 0x000000], skeleton: [0xc1c1c1, 0x494949], spider: [0x342d27, 0xa80e0e] };
    Object.keys(EGGS).forEach(function (m) {
      var pal = mat(EGGS[m][0]); pal.d = shade(EGGS[m][0], 0.35);
      var c = icon(m + '_spawn_egg', EGG, pal); var ctx = c.getContext('2d'); ctx.fillStyle = hex(EGGS[m][1]);
      [[6, 5], [9, 7], [5, 9], [8, 10], [10, 4], [7, 12]].forEach(function (p) { ctx.fillRect(p[0], p[1], 1, 1); });
    });
    // missing fallback
    icon('missing', ['dddddddddddddddd', 'd..............d', 'd.pp.pp.pp.pp..d', 'd..............d', 'd.pp.pp.pp.pp..d', 'd..............d', 'd.pp.pp.pp.pp..d', 'd..............d', 'd.pp.pp.pp.pp..d', 'd..............d', 'd.pp.pp.pp.pp..d', 'd..............d', 'd.pp.pp.pp.pp..d', 'd..............d', 'd..............d', 'dddddddddddddddd'], { d: 0x000000, p: 0xf800f8 });
  }

  function get(name) { build(); return ICONS[name] || null; }
  MC.ItemIcons = { build: build, get: get, ICONS: ICONS };
})();
